 
---
- hosts: localhost  

  vars:
    USE_SERVERGC : true

  tasks:  


    # - name: print
    #   debug:
    #     msg: "{{ ansible_devices }}"

    # - name: print
    #   debug:
    #     msg: "{{(ansible_facts.memtotal_mb /1024 | int  )}}"     
       
    - name: Identificando quantidade minima de memoria
      ansible.builtin.set_fact:
        USE_SERVERGC : false
      when: (ansible_facts.memtotal_mb /1024 | int) < korp_data_memory_minimum_size

    - name: print
      debug:
        msg: "{{free_disks}}"




  # - name: Mapeamento de discos livres
  #   ansible.builtin.set_fact:
  #     free_disks: "{{ free_disks | union([item]) }}"
  #   when: ansible_devices[item].partitions | list | length==0
  #   with_items: "{{ ansible_devices.keys() | map('regex_search', 'sd.*') | select('string') | list  }}"