---
- hosts: localhost  

  vars:
    free_disks: true

  tasks:  


    # - name: print
    #   debug:
    #     msg: "{{ ansible_devices }}"

    # - name: print
    #   debug:
    #     msg: "{{(ansible_facts.memtotal_mb /1024 | int  )}}"        

    - name: Mapeamento de discos livres
      ansible.builtin.set_fact:
        free_disks: false
      when: (ansible_facts.memtotal_mb /1024 | int) < 12

    - name: print
      debug:
        msg: "{{free_disks}}"