---
- hosts: localhost
  tasks:
    # - name: Checagem se Possui dois SQL Server
    #   ansible.builtin.pause:        
    #     prompt: "Para continuar a instalação, digite as seguintes informações sobre o servidor SQL Server: Possui 2 banco de dados  SQL? Exemplo : Homologação e  Produção? S - sim N - nao"
    #   register: Chk_sql

    # - name: testing_sql_ip_whenChkEqualsN
    #   ansible.builtin.set_fact:
    #     testing_sql_ip: "{{ lookup('community.general.random_string', base64=True) }} "
    #   when:   Chk_sql.user_input |upper == "N" 

      

    # - name: "Read a file content"
    #   shell: |
    #     cat /proc/sys/kernel/random/uuid
    #   register: file_content

    - name: testing_sql_ip_whenchkequalsn
      ansible.builtin.set_fact:
        testing_sql_ip: "{{ lookup('community.general.random_string') }}"  

    # - name : Sql_testing_pass
    #   ansible.builtin.pause:        
    #     prompt: "Senha do usuário do sql de Homologação: "  
    #   register: testing_sql_ip    


     

    - name: Encrypt stuff with Ansible-Vault
      shell:
        cmd: sudo mkdir -p /etc/korp/ansible/;echo "{{ testing_sql_ip }}" | sudo tee /etc/korp/ansible/.vault_key > /dev/null;sudo chown root:root /etc/korp/ansible/.vault_key;sudo chmod 444 /etc/korp/ansible/.vault_key;touch /etc/korp/ansible/inventory.yml;echo """[defaults]inventory = /etc/korp/ansible/inventory.yml""" | sudo tee /etc/ansible/ansible.cfg > /dev/null
      
    - name: encrypt
      shell:
        cmd: sudo ansible-vault encrypt /etc/korp/ansible/inventory.yml --vault-id /etc/korp/ansible/.vault_key
       
        
    



    - name: teste
      debug:
        var: testing_sql_ip
         

  #   - name : random UUID
  #       gather_fact: no 
  # vars:
  #   introspection_secret : "{{ 1000 | random | to_uuid | upper  }}"
  # - set_fact :
  #       introspection_secret="{{ 1000 | random | to_uuid | upper  }}"
  #     -debug var=introspection_secret