---
- hosts: localhost  

  tasks:  
    - name: senha   
      ansible.builtin.set_fact:
        mssql_korp_passRandom: "{{ lookup('community.general.random_string',special=False) }}"    

    - name: print
      debug:
        msg: "{{ mssql_korp_passRandom }}"
