---
- hosts: localhost

  tasks:  
      #importinventoryfile
    - name: ImportarInventario
      ansible.builtin.set_fact:
        inventory: "{{ (lookup('ansible.builtin.template', '/root/repositorios/test.yaml')|from_yaml) }}"

    - name: caminhodoInventario
      ansible.builtin.set_fact:
        path_inventory: inventory.all.children.nodes.hosts.localhost

    - name: templateInventory
      ansible.builtin.set_fact:
        inventory:
          all:
            children:
              nodes:
                hosts:
                  localhost: 
      when:
        - inventory.all.children.nodes.hosts.localhost is not defined 
    - name: app_server
      ansible.builtin.set_fact:      
         inventory:
          all:
            children:
              nodes:
                hosts:
                  localhost: "{{ inventory.all.children.nodes.hosts.localhost | combine(
                    {
                       'app_server' : {
                          'address' : path_inventory.app_server.addess | default ( 'l')                   
                       }
                    }, 
                      recursive=True) }}"
    - name: linux_korp
      ansible.builtin.set_fact:      
         inventory:
          all:
            children:
              nodes:
                hosts:
                  localhost: "{{ inventory.all.children.nodes.hosts.localhost | combine(
                    {
                     'linux_korp' : {
                    'user' : path_inventory.linux_korp.user | default ( 'l') ,
                    'password' : path_inventory.linux_korp.password | default ( 'l')                                   
                    }
                    }, 
                      recursive=True) }}"
    - name: self_signed_cert
      ansible.builtin.set_fact:      
         inventory:
          all:
            children:
              nodes:
                hosts:
                  localhost: "{{ inventory.all.children.nodes.hosts.localhost | combine(
                    {
                       'self_signed_cert' :{
                        'passphrase' : path_inventory.self_signed_cert.passphrase | default ( 'l')                              
                       }
                    }, 
                      recursive=True) }}"
    - name: mssql
      ansible.builtin.set_fact:      
         inventory:
          all:
            children:
              nodes:
                hosts:
                  localhost: "{{ inventory.all.children.nodes.hosts.localhost | combine(
                    {
                       'mssql' : {
                         'address' : path_inventory.mssql.address | default ( 'l'), 
                         'default_user' : path_inventory.mssql.default_user | default ( 'l') , 
                         'default_password' : path_inventory.mssql.default_password | default ( 'l') , 
                         'korp_user' : path_inventory.mssql.korp_user | default ( 'l') , 
                         'korp_password' : path_inventory.mssql.korp_password | default ( 'l')                   
                       }
                    }, 
                      recursive=True) }}"
    - name: testing_mssql
      ansible.builtin.set_fact:      
         inventory:
          all:
            children:
              nodes:
                hosts:
                  localhost: "{{ inventory.all.children.nodes.hosts.localhost | combine(
                    {
                       'mssql' : {
                         'address' : path_inventory.mssql.address | default ( address ), 
                         'default_user' : path_inventory.mssql.default_user | default ( default_user ) , 
                         'default_password' : path_inventory.mssql.default_password | default ( default_password) , 
                         'korp_user' : path_inventory.mssql.korp_user | default (korp_user) , 
                         'korp_password' : path_inventory.mssql.korp_password | default (korp_password)                   
                       }
                    }, 
                      recursive=True) }}"                         
    - name: postgres
      ansible.builtin.set_fact:      
         inventory:
          all:
            children:
              nodes:
                hosts:
                  localhost: "{{ inventory.all.children.nodes.hosts.localhost | combine(
                    {
                       'postgres' : {
                         'address' : path_inventory.postgres.address | default ( 'l') , 
                         'default_user' : path_inventory.postgres.default_user | default ( 'l') , 
                         'default_password' : path_inventory.postgres.default_password |  default ( 'l'), 
                         'korp_user' : path_inventory.postgres.korp_user | default ( 'l'), 
                         'korp_password' : path_inventory.postgres.korp_password | default ( 'l')                   
                       }
                    }, 
                      recursive=True) }}"
    - name: rabbitmq
      ansible.builtin.set_fact:      
         inventory:
          all:
            children:
              nodes:
                hosts:
                  localhost: "{{ inventory.all.children.nodes.hosts.localhost | combine(
                    {
                       'rabbitmq' : {
                         'korp_user' : path_inventory.rabbitmq.korp_user | default ( 'l') , 
                         'korp_password' : path_inventory.rabbitmq.korp_password | default ( 'l')                    
                       }
                    }, 
                      recursive=True) }}"
    - name: redis
      ansible.builtin.set_fact:      
         inventory:
          all:
            children:
              nodes:
                hosts:
                  localhost: "{{ inventory.all.children.nodes.hosts.localhost | combine(
                    {
                       'redis' : {
                          'password' : path_inventory.redis.password | default ( 'l')                    
                       }
                    }, 
                      recursive=True) }}"
    - name: minio
      ansible.builtin.set_fact:      
         inventory:
          all:
            children:
              nodes:
                hosts:
                  localhost: "{{ inventory.all.children.nodes.hosts.localhost | combine(
                    {
                       'minio' : {
                          'acess_key' : path_inventory.minio.acess_key | default ( 'l') ,
                          'secret_key' : path_inventory.minio.secret_key| default ( 'l')                     
                       }
                    }, 
                      recursive=True) }}"
    - name: general
      ansible.builtin.set_fact:      
        inventory:
          all:
            children:
              nodes:
                hosts:
                  localhost: "{{ inventory.all.children.nodes.hosts.localhost | combine(
                    {
                      'general' : {
                          'introspection_secret' : path_inventory.general.introspection_secret | default ( 'l')       
                       }
                    }, 
                      recursive=True) }}"
      #Funcao de inserir a variavel no arquivo.
    - name: Write variable to file
      copy:
        content: '{{inventory | to_nice_yaml(indent=2) }}'
        dest: /root/repositorios/test.yaml
      delegate_to: localhost
      
    - name: teste
      debug:
        msg: "{{ inventory }}" 

